source 'https://github.com/igagis/cocoapods-repo.git'

project 'morda/morda.xcodeproj'

platform :ios, '8.0'

target "morda" do
	pod 'utki', '>= 1.1.30'
	pod 'libpapki', '>= 1.0.3'
	pod 'libkolme', '>= 1.0.1'
	pod 'puu', '>= 0.1.1'
	pod 'libsvgren', '>= 0.3.3'
	pod 'libnitki', '>= 1.0.0'
	pod 'libpng_igagis', '>= 1.4.1'
	pod 'freetype', '>= 2.6.4'
	pod 'libjpeg', '>= 6.1.1'
end
