source 'https://github.com/cppfw/cocoapods-repo.git'

project 'morda/morda.xcodeproj'

platform :ios, '13.0'

target "morda" do
	pod 'utki', '>= 1.1.124'
	pod 'papki', '>= 1.0.93'
	pod 'r4', '>= 1.0.53'
	pod 'treeml', '>= 0.1.28'
	pod 'svgdom', '>= 0.3.61'
	pod 'svgren', '>= 0.5.11'
	pod 'nitki', '>= 1.0.41'
	pod 'freetype', '>= 2.10.1.9'
	pod 'rasterimage', '>= 0.1.4'
end
