source 'https://github.com/igagis/cocoapods-repo.git'

project 'morda/morda.xcodeproj'

platform :ios, '8.0'

target "morda" do
	pod 'utki', '>= 1.1.30'
	pod 'papki', '>= 1.0.58'
	pod 'libkolme', '>= 1.0.1'
	pod 'puu', '>= 0.1.1'
	pod 'svgren', '>= 0.4.59'
	pod 'nitki', '>= 1.0.22'
	pod 'png', '>= 1.4.1.4'
	pod 'freetype', '>= 2.10.1.1'
	pod 'jpeg', '>= 6.1.1.5'
end
