# Creating basic application

Install *morda* on your system.

This sample uses link:https://github.com/igagis/mordavokne[*mordavokne*] complementary library as OS adaptation layer, so install it on your system too.

Entry point of the *mordavokne* application is a method called _mordavokne::createApp()_, and not a traditional _main()_.
Morda defines _main()_ internally, so the user should not define _main()_.

User should derive their _Application_ class from _mordavokne::App_, which will be a singleton class. Then, return an instance of that class from _mordavokne::createApp()_. To do that, in `main.cpp` include necessary morda files:

[source,c++]
....
#include <mordavokne/App.hpp>
#include <mordavokne/AppFactory.hpp>
....

Then we define our Application class as forllows
[source,c++]
....
class Application : public mordavokne::App{
public:
	Application() :
			mordavokne::App(mordavokne::App::WindowParams(r4::vec2ui(800, 600)))
	{
		// Here we will do all the initializations of our app, like loading the UI etc.
	}
};
....

And then we define the `mordavokne::create_application()` function
[source,c++]
....
std::unique_ptr<mordavokne::App> mordavokne::create_application(int argc, const char** argv){
	return utki::makeUnique<Application>();
}
....

So, now we can build and run the project, but it will display just an empty window.

Now, lets add some UI. We want to use standard *morda* widgets, so, let's initialize them in the Application constructor
[source,c++]
....
class Application : public mordavokne::App{
public:
	Application() :
			mordavokne::App(mordavokne::App::WindowParams(r4::vec2ui(800, 600)))
	{
		this->gui.initStandardWidgets(*this->get_res_file());
	}
};
....

Let's describe our GUI using the GUI script. Create a file named _main.gui._ in the _res/_ directory of your project with following contents
....
@pile{// frame layout places widgets in the center one on top of another
	@column{ // vertical area layout places widgets one below each other
		@push_button{
			id{hw_button} // we can find this button by ID from code
			@text{
				text{"Hello world!!!"}
			}
		}

		@text{
			id{info_text} // we can find this label by ID from code
			text{Information}
		}
	}
}
....


Now we need to "inflate" the GUI from script in the code and set it to application:
[source,c++]
....
class Application : public mordavokne::App{
public:
	Application() :
			mordavokne::App(mordavokne::App::WindowParams(kolme::Vec2ui(800, 600)))
	{
		this->gui.initStandardWidgets(*this->get_res_file());

		// Inflate widgets hierarchy from GUI description script
		auto c = this->gui.context->inflater.inflate(
				*this->createResourceFileInterface("res/main.gui.")
			);

		// set the widgets hierarchy to the application
		this->gui.set_root(c);
	}
};
....

After running the app we will see a button and a text label below it. But pressing the button will do nothing.
Let's add some action on the button press
[source,c++]
....
#include <mordavokne/App.hpp>
#include <mordavokne/AppFactory.hpp>

#include <morda/widgets/label/Text.hpp>
#include <morda/widgets/button/Button.hpp>


class Application : public mordavokne::App{
public:
	Application() :
			mordavokne::App(mordavokne::App::WindowParams(r4::vec2ui(800, 600)))
	{
		this->gui.initStandardWidgets(*this->get_res_file());

		// Inflate widgets hierarchy from GUI description script
		auto c = this->gui.context->inflater.inflate(
				*this->get_res_file("res/main.gui")
			);

		// set the widgets hierarchy to the application
		this->gui.set_root(c);

		auto textLabel = c->try_get_widget_as<morda::Text>("info_text");
		ASSERT(textLabel)

		auto button = c->try_get_widget_as<morda::PushButton>("hw_button");

		auto textLabelWeak = utki::make_weak(textLabel); // make a weak pointer to the TextLabel widget.

		bool even = true;

		// connect some action on button click
		button->clicked = [textLabelWeak, even](morda::PushButton&) mutable {
			if(auto tl = textLabelWeak.lock()){
				even = !even;
				if(even){
					tl->setText("even");
				}else{
					tl->setText("odd");
				}
			}
		};
	}
};



std::unique_ptr<mordavokne::App> mordavokne::create_application(int argc, const char** argv){
	return utki::makeUnique<Application>();
}
....
Now we can run the app and press the button and see that it will do something :).

